// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ScrapeTask { id: string, ctime: string, project_id: string, done: boolean, title: string, href: string, desc?: string, }