// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ScrapeTaskForCreate { project_id: string, title: string, href: string, done?: boolean, desc?: string, }