[build]
beforeBuildCommand = ""
beforeDevCommand = ""
devPath = "http://localhost:8080/"
distDir = "../dist"

[package]
productName = "quantix-dapp"
version = "0.1.0"

[tauri.allowlist]
all = false

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = [ ]
icon = [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico"
      ]
identifier = "my.dapp"
longDescription = ""
resources = [ ]
shortDescription = ""
targets = "all"

[tauri.bundle.deb]
depends = [ ]

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = [ ]

[tauri.bundle.windows]
digestAlgorithm = "sha256"
timestampUrl = ""

[tauri.security]
# csp = null

[[tauri.security.dangerousRemoteDomainIpcAccess]]
domain = "fund.eastmoney.com"
windows = ["main", "Scraper_0", "Scraper_1", "Scraper_2", "Scraper_3", "Scraper_4", "Scraper_5", "Scraper_6", "Scraper_7", "Scraper_8", "Scraper_9"]
enableTauriAPI = true

[[tauri.security.dangerousRemoteDomainIpcAccess]]
domain = "quote.eastmoney.com"
windows = ["main", "Scraper_0", "Scraper_1", "Scraper_2", "Scraper_3", "Scraper_4", "Scraper_5", "Scraper_6", "Scraper_7", "Scraper_8", "Scraper_9"]
enableTauriAPI = true

[[tauri.security.dangerousRemoteDomainIpcAccess]]
domain = "fundf10.eastmoney.com"
windows = ["main", "Scraper_0", "Scraper_1", "Scraper_2", "Scraper_3", "Scraper_4", "Scraper_5", "Scraper_6", "Scraper_7", "Scraper_8", "Scraper_9"]
enableTauriAPI = true

[[tauri.security.dangerousRemoteDomainIpcAccess]]
domain = "finance.yahoo.com"
windows = ["main", "Scraper_0", "Scraper_1", "Scraper_2", "Scraper_3", "Scraper_4", "Scraper_5", "Scraper_6", "Scraper_7", "Scraper_8", "Scraper_9"]
enableTauriAPI = true

[[tauri.security.dangerousRemoteDomainIpcAccess]]
domain = "s.yimg.com"
windows = ["main", "Scraper_0", "Scraper_1", "Scraper_2", "Scraper_3", "Scraper_4", "Scraper_5", "Scraper_6"," Scraper _7"," Scraper _8"," Scraper _9"]
enableTauriAPI = true



[tauri.updater]
active = false

[[tauri.windows]]
title = "quantix-dapp"
fullscreen = false
resizable = true
