// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FundNetValue } from "./FundNetValue";
import type { ProductValue } from "./ProductValue";
import type { ShopValue } from "./ShopValue";
import type { StoreValue } from "./StoreValue";
import type { StringValue } from "./StringValue";

export type DataValue = { "StoreValue": StoreValue } | { "ShopValue": ShopValue } | { "ProductValue": ProductValue } | { "FundNetValue": FundNetValue } | { "StringValue": StringValue };