// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface HTMLAnchorElementValue { title: string | null, href: string, inner_text: string, scraped_date: number, }