// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface StoreValue { date: string, unit_value: number, cumulate_value: number, daily_rate: number, }